version: 2.1
executors:
  fedora:
    docker:
      - image: registry.fedoraproject.org/fedora
    shell: /usr/bin/bash

jobs:
  build:
    executor: fedora
    steps:
      - run:
          name: Install dependencies
          command: >
            sudo dnf install --assumeyes --setopt=install_weak_deps=False
            cmake gcc git make SDL-devel
      - checkout
      - run:
          name: Generate Makefiles
          command: >
            cmake -B build/ -S ./
      - run:
          name: Build
          command: >
            cmake --build build/

workflows:
  build:
    jobs:
      - build
