version: 2.1
executors:
  fedora:
    docker:
      - image: registry.fedoraproject.org/fedora
    shell: /usr/bin/bash

jobs:
  build:
    executor: fedora
    steps:
      - run:
          name: Install dependencies
          command: >
            sudo dnf install --assumeyes --setopt=install_weak_deps=False
            cmake gcc git make SDL-devel
      - checkout
      - run:
          name: Generate Makefiles
          command: >
            cmake -B build/ -S ./
      - run:
          name: Build
          command: >
            cmake --build build/

  fmt:
    executor: fedora
    steps:
      - run:
          name: Install dependencies
          command: >
            sudo dnf install --assumeyes --setopt=install_weak_deps=False
            clang-tools-extra git
      - checkout
      - run:
          name: Reformat
          command: >
            clang-format -i src/*.c src/*.h
      - run:
          name: Compare
          command: >
            git diff -U4 --histogram --exit-code

workflows:
  build:
    jobs:
      - build
      - fmt
